# Generated by Django 4.0.6 on 2022-07-31 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('nombre', '-camada')},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ('apellido', 'nombre')},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ('apellido', 'nombre')},
        ),
        migrations.AddField(
            model_name='entregable',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'camada')},
        ),
        migrations.AlterUniqueTogether(
            name='estudiante',
            unique_together={('nombre', 'apellido', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='profesor',
            unique_together={('apellido', 'nombre', 'email', 'profesion')},
        ),
    ]
